version: "3"
services:
  rdbms:
    image: postgres
    container_name: goyotashi-database
    ports:
    - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: goyotashi
      TZ: Asia/Tokyo
    volumes:
    - goyotashi-data-postgre:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d

volumes:
  goyotashi-data-postgre: