version: "3"
services:
  web:
    build: .
    restart: always
    environment:
      TZ: Asia/Tokyo
      DATABASE_URL: rdbms
      ROCKET_ENV: production
    command: "cargo run --release"
    networks:
      - home
      - default
    links:
      - rdbms

  rdbms:
    image: postgres
    container_name: goyotashi-database
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: goyotashi
      TZ: Asia/Tokyo
    volumes:
      - goyotashi-data-postgre-prod:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  goyotashi-data-postgre-prod:

networks:
  home:
    external: true