version: "3"
services:
  server:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - portal-certificate:/var/lib/https-portal
    links:
      - web
    environment:
      DOMAINS: 'api.goyotashi.com -> http://web:8000'
      STAGE: 'production'

  web:
    build: .
    restart: always
    environment:
      TZ: Asia/Tokyo
      DATABASE_URL: rdbms
    command: "cargo run"
    links:
      - rdbms

  rdbms:
    image: postgres
    container_name: goyotashi-database
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: goyotashi
      TZ: Asia/Tokyo
    volumes:
      - goyotashi-data-postgre-prod:/var/lib/postgresql/data

volumes:
  goyotashi-data-postgre-prod:
  portal-certificate: